export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          business_name: string | null;
          business_logo_url: string | null;
          business_address: string | null;
          business_phone: string | null;
          business_email: string | null;
          business_website: string | null;
          tax_id: string | null;
          vat_number: string | null;
          bank_details: Json | null;
          default_currency: string;
          default_language: string;
          stripe_account_id: string | null;
          paypal_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          business_name?: string | null;
          business_logo_url?: string | null;
          business_address?: string | null;
          business_phone?: string | null;
          business_email?: string | null;
          business_website?: string | null;
          tax_id?: string | null;
          vat_number?: string | null;
          bank_details?: Json | null;
          default_currency?: string;
          default_language?: string;
          stripe_account_id?: string | null;
          paypal_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_name?: string | null;
          business_logo_url?: string | null;
          business_address?: string | null;
          business_phone?: string | null;
          business_email?: string | null;
          business_website?: string | null;
          tax_id?: string | null;
          vat_number?: string | null;
          bank_details?: Json | null;
          default_currency?: string;
          default_language?: string;
          stripe_account_id?: string | null;
          paypal_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          company: string | null;
          email: string;
          phone: string | null;
          address: string | null;
          city: string | null;
          postal_code: string | null;
          country: string | null;
          vat_number: string | null;
          language_preference: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          company?: string | null;
          email: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          country?: string | null;
          vat_number?: string | null;
          language_preference?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          company?: string | null;
          email?: string;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          country?: string | null;
          vat_number?: string | null;
          language_preference?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      proposals: {
        Row: {
          id: string;
          user_id: string;
          client_id: string;
          proposal_number: string;
          title: string;
          template_id: string;
          language: string;
          content: Json;
          items: Json;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          discount_amount: number;
          total_amount: number;
          currency: string;
          status: 'draft' | 'sent' | 'viewed' | 'signed' | 'rejected' | 'expired';
          valid_until: string | null;
          signed_at: string | null;
          signature_data: string | null;
          signer_name: string | null;
          signer_email: string | null;
          view_count: number;
          last_viewed_at: string | null;
          pdf_url: string | null;
          share_token: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          client_id: string;
          proposal_number: string;
          title: string;
          template_id: string;
          language?: string;
          content: Json;
          items: Json;
          subtotal: number;
          tax_rate?: number;
          tax_amount: number;
          discount_amount?: number;
          total_amount: number;
          currency?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'signed' | 'rejected' | 'expired';
          valid_until?: string | null;
          signed_at?: string | null;
          signature_data?: string | null;
          signer_name?: string | null;
          signer_email?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          pdf_url?: string | null;
          share_token?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          client_id?: string;
          proposal_number?: string;
          title?: string;
          template_id?: string;
          language?: string;
          content?: Json;
          items?: Json;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          currency?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'signed' | 'rejected' | 'expired';
          valid_until?: string | null;
          signed_at?: string | null;
          signature_data?: string | null;
          signer_name?: string | null;
          signer_email?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          pdf_url?: string | null;
          share_token?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          user_id: string;
          client_id: string;
          proposal_id: string | null;
          invoice_number: string;
          template_id: string;
          language: string;
          items: Json;
          subtotal: number;
          tax_rate: number;
          tax_amount: number;
          discount_amount: number;
          total_amount: number;
          currency: string;
          status: 'draft' | 'sent' | 'viewed' | 'paid' | 'partially_paid' | 'overdue' | 'cancelled';
          payment_method: 'stripe' | 'paypal' | 'bank_transfer' | 'cash' | 'other' | null;
          payment_terms: string;
          issue_date: string;
          due_date: string;
          paid_amount: number;
          paid_at: string | null;
          stripe_payment_intent_id: string | null;
          paypal_order_id: string | null;
          notes: string | null;
          footer_text: string | null;
          view_count: number;
          last_viewed_at: string | null;
          pdf_url: string | null;
          share_token: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          client_id: string;
          proposal_id?: string | null;
          invoice_number: string;
          template_id: string;
          language?: string;
          items: Json;
          subtotal: number;
          tax_rate?: number;
          tax_amount: number;
          discount_amount?: number;
          total_amount: number;
          currency?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'paid' | 'partially_paid' | 'overdue' | 'cancelled';
          payment_method?: 'stripe' | 'paypal' | 'bank_transfer' | 'cash' | 'other' | null;
          payment_terms?: string;
          issue_date: string;
          due_date: string;
          paid_amount?: number;
          paid_at?: string | null;
          stripe_payment_intent_id?: string | null;
          paypal_order_id?: string | null;
          notes?: string | null;
          footer_text?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          pdf_url?: string | null;
          share_token?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          client_id?: string;
          proposal_id?: string | null;
          invoice_number?: string;
          template_id?: string;
          language?: string;
          items?: Json;
          subtotal?: number;
          tax_rate?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          currency?: string;
          status?: 'draft' | 'sent' | 'viewed' | 'paid' | 'partially_paid' | 'overdue' | 'cancelled';
          payment_method?: 'stripe' | 'paypal' | 'bank_transfer' | 'cash' | 'other' | null;
          payment_terms?: string;
          issue_date?: string;
          due_date?: string;
          paid_amount?: number;
          paid_at?: string | null;
          stripe_payment_intent_id?: string | null;
          paypal_order_id?: string | null;
          notes?: string | null;
          footer_text?: string | null;
          view_count?: number;
          last_viewed_at?: string | null;
          pdf_url?: string | null;
          share_token?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      time_entries: {
        Row: {
          id: string;
          user_id: string;
          client_id: string | null;
          project_name: string | null;
          task_description: string | null;
          hours: number;
          minutes: number;
          hourly_rate: number | null;
          total_amount: number | null;
          date: string;
          start_time: string | null;
          end_time: string | null;
          billable: boolean;
          invoiced: boolean;
          invoice_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          client_id?: string | null;
          project_name?: string | null;
          task_description?: string | null;
          hours: number;
          minutes?: number;
          hourly_rate?: number | null;
          total_amount?: number | null;
          date: string;
          start_time?: string | null;
          end_time?: string | null;
          billable?: boolean;
          invoiced?: boolean;
          invoice_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          client_id?: string | null;
          project_name?: string | null;
          task_description?: string | null;
          hours?: number;
          minutes?: number;
          hourly_rate?: number | null;
          total_amount?: number | null;
          date?: string;
          start_time?: string | null;
          end_time?: string | null;
          billable?: boolean;
          invoiced?: boolean;
          invoice_id?: string | null;
          created_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          price: number;
          unit: string;
          tax_rate: number;
          category: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          price: number;
          unit?: string;
          tax_rate?: number;
          category?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          unit?: string;
          tax_rate?: number;
          category?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
